//
//  RTECategory.swift
//  RTE
//
//  Created by Özcan AKKOCA on 6.06.2017.
//  Copyright © 2017 Özcan AKKOCA. All rights reserved.
//

import Foundation

class RTECategory {

    
    var genel1Dict : NSDictionary = [ "Bakınız" : "bakiniz",
                                      "Annesi Bu Beni Niye Bu Kadar Çok Seviyor" : "annesi_bu_beni_niye_bu_kadar_cok_seviyor",
                                      "Çok Sevindim" : "cok_sevindim",
                                      "Hoşgeldiniz" : "hosgeldiniz",
                                      "Ciddimi Diyorsun" : "ciddimi_diyorsun",
                                      "Bak Neler Söylüyor Neler" : "bak_neler_soyluyor_neler",
                                      "Ne Yapayım Ben Bunu" : "ne_yapayim_ben_bunu",
                                      "Elinize Sağlık" : "elinize_saglik",
                                      "Yok Ya" : "yok_ya",
                                      "Ey Gidi Günler" : "ey_gidi_gunler",
                                      "Herkes İşin Lafında" : "herkes_isin_lafinda",
                                      "Öldürdü Beni Be" : "oldurdu_beni_be",
                                      "Olmaz Olmaz" : "olmaz_olmaz",
                                      "Böyle Geldik Böyle Gidiyoruz" : "boyle_geldik_boyle_gidiyoruz",
                                      "Eyy Kardeşlerim" : "eyy_kardeslerim",
                                      "Zor Geliyor Kardeşim" : "zor_geliyor_kardasim",
                                      "Geçiktim Hakkınızı Helal Edin" : "geciktim_hakkinizi_helal_edin",
                                      "Haklısınız" : "haklisiniz",
                                      "Kalın Sağlıcakla" : "kalin_saglicakla",
                                      "Bende Şaşırdım" : "bende_sasirdim",
                                      "Aman Sabırlı Olun" : "aman_sabirli_olun",
                                      "Ve Aleyküm Selam" : "ve_aleykum_selam",
                                      "Alan Götürdü Alan Götürdü" : "alan_goturdu_alan_goturdu",
                                      "Aldatmayın Çocukları" : "aldatmayin_cocuklari",
                                      "Bu Nasıl Bir Anlayıştır" : "bu_nasil_bir_anlayistir",
                                      "Bu Ne Biçim İştir" : "bu_ne_bicim_istir",
                                      "Eh Sallana Sallana" : "eh_sallana_sallana",
                                      "Ya Ben Demedim" : "ya_ben_demedim",
                                      "Geçin Bunları Geçin" : "gecin_bunlari_gecin",
                                      "Kimi Aldatıyorusunuz Ya" : "kimi_aldatiyorsunuz_ya",
                                      "Ama Ya Rabbim" : "aman_ya_rabbim",
                                      "Size Ne Ya" : "size_ne_ya",
                                      "Onlar Mazide Kaldı" : "onlar_mazide_kaldi",
                                      "Öyle Bir Haykır Ki" : "oyle_bir_haykir_ki",
                                      "Cirit Atıyor Cirit" : "cirit_atiyor_cirit",
                                      "Ne Yaptınız" : "ne_yaptiniz",
                                      "Geçti O" : "gecti_o",
                                      "OOOO" : "oooo",
                                      "Neyy" : "neyy",
                                      "Ah" : "ah_ah"
                            
                                    ]
    
    var genel2Dict : NSDictionary = ["Sabah Dört Buçuğa Kadar Konuşuyoruz":"sabah_dort_bucuga_kadar_konusuyoruz",
                                     "Maaşallah Allah Nazardan Saklasın":"maasallah_allah_nazardan_saklasin",
                                     "Vah Zavallı Vah":"vah_zavalli_vah",
                                     "Bıktık Ya Bıktık":"biktik_ya_biktik",
                                     "Yazıklar Olsun Sizlere":"yaziklar_olsun_sizlere",
                                     "Yalan Konuşma Be":"yalan_konusma_be",
                                     "Ben Seni Varya Bu Kadar Seviyorum":"ben_seni_varya_bu_kadar_seviyorum",
                                     "Reisim Neredeyiz Biliyormusun":"reisim_neredeyiz_biliyormusun",
                                     "Gençler Gençler":"gencler_gencler",
                                     "Ders Çalış Ders":"ders_calis_ders",
                                     "Nadani Terk Etmedin Yarani Arzularsın":"nadani_terk_etmedin_yarani_arzularsin",
                                     "Biz Nadanı Terk Ettik Yaranı Bulduk":"biz_nadani_terk_ettik_yarani_bulduk",
                                     "Kızlar Kızlar":"kizlar_kizlar",
                                     "Ya Sanane Ya":"ya_sanane_ya",
                                     "Estaizubilllah Bismillah":"estaizubillah_bismillah",
                                     "Ne Diyor Bu Adam Ya":"ne_diyor_bu_adam_ya",
                                     "Ne Oldum Deme Ne Olacağım De":"ne_oldum_deme_ne_olacagim_de",
                                     "Ne Yapacağınızı Biliyorsunuz Değil Mi":"ne_yapacaginizi_biliyorsunuz_degil_mi"
                                    ]
    var genel3Dict : NSDictionary = ["Selamun Aleyküm" : "selamun_aleykum",
                                     "Seni Saygıyla Selamlıyorum" : "seni_saygiyla_selamliyorum",
                                     "Seni Gönül Dolusu Muhabbet ile Selamlıyorum" : "seni_gonul_dolusu_muhabbet_ile_selamliyorum",
                                     "Senin Gidecek Yerin Yok Be" : "senin_gidecek_yerin_yok_be",
                                     "Sakin Olun" : "sakin_olun",
                                     "Sen Kimsin Ya" : "sen_kimsin_ya",
                                     "Allah Kabul Etsin" : "allah_kabul_etsin",
                                     "Geliyorum Şimdi" : "geliyorum_simdi",
                                     "Doğrusu Şevkini Kırmak İstemiyorum" : "dogrusu_sevkini_kirmak_istemiyorum",
                                     "Görüyormusun Burada Bile Selfie Yapıyor" : "goruyormusun_burada_bile_selfie_yapiyor",
                                     "Hadi Oradan Ahlaksız" : "hadi_oradan_ahlaksiz",
                                     "Hadi Gülüm Yandan Yandan" : "hadi_gulum_yandan_yandan",
                                     "Ne Olacak" : "ne_olacak",
                                     "Olsun Be" : "olsun_be",
                                     "Kafaya Bak Ya" : "kafaya_bak_ya",
                                     "Ben Senin EEEE" : "ben_senin_eeee",
                                     "Bakalım Göreceğiz" : "bakalim_gorecegiz",
                                     "Bene Bak Akedes" : "bene_bak_akedes",
                                     "Maaşallahınız Var" : "maasallahiniz_var",
                                     "Buyrun Buyrun Buyrun" : "buyrun_buyrun_buyrun",
                                     "Bak Bak Bak" : "bak_bak_bak",
                                     "Yerinde Duramıyor" : "yerinde_duramiyor",
                                     "Ağlarım Anlatamam" : "aglarim_anlatamam",
                                     "Hissederim Söyleyemem" : "hissederim_soyleyemem",
                                     "Burası Enteresan" : "burasi_enteresan",
                                     "Boşuna Uğraşmayın" : "bosuna_ugrasmayin",
                                     "Biz Ölümüne" : "biz_olumune",
                                     "Şaka Maka Baya Seyircim Varmış" : "saka_maka_baya_seyircim_varmis"
                                    ]
    var meclisDict : NSDictionary = ["Nereye Hitap Edileceğini Bilirim" : "nereye_hitap_edilecegini_bilirim",
                                     "Bitmedi Bak" : "bitmedi_bak",
                                     "Bunlar Dürüst Değil" : "bunlar_durust_degil",
                                     "Çok Konuşuyorsun" : "cok_konusuyorsun",
                                     "Bu Kürsülerin Acemisiniz" : "bu_kursulerin_acemisisiniz",
                                     "Siz Mi Susturacaksınız Ben Mi Susturayım" : "siz_mi_susturacaksiniz_ben_mi_susturayim",
                                     "Onu Özele Gelirsin Anlatırım Sana" : "onu_ozele_gelirsin_anlatirim_sana",
                                     "Ne Yapayım Ben Bunu" : "ne_yapayim_ben_bunu",
                                     "Nabza Göre Şerbet Veriyorlar" : "nabza_gore_serbet_veriyorlar",
                                     "Tahriklerinize Gelecek Değilim" : "tahriklerinize_gelecek_degilim",
                                     "İşte Bu Olmadı" : "iste_bu_olmadi",
                                     "Baki Kalan Bu Kubbede Hoş Bir Sada İmiş" : "baki_kalan_bu_kubbede_hos_bir_sada_imis",
                                     "Lütfen Susarmısınız Lütfen" : "lutfen_susar_misiniz_lutfen",
                                     "Hoplama Rahat Ol" : "hoplama_rahat_ol",
                                     "Niye Rahatsız Oluyorsun" : "niye_rahatsiz_oluyorsun",
                                     "Okulu Asıp Haysızlığa Gitmişler" : "okulu_asip_haylazliga_gitmisler",
                                     "Az Önce Bir İfade Kullanıldı" : "az_once_bir_ifade_kullanildi",
                                     "Ben Sayıyorum" : "ben_sayiyorum",
                                     "Artık Ciddi Olarak Ele Alalım" : "artik_ciddi_olarak_ele_alalim",
                                     "Al Hepsi Burada" : "al_hepsi_burada",
                                     "Önce Başkanını Davet Et" : "once_baskanini_davet_et",
                                     "Kara Bulut Gibi Çöktü" : "kara_bulut_gibi_coktu",
                                     "Geçiken Adalet Adalet Değildir" : "geciken_adalet_adalet_degildir",
                                     "Devamlı Yaptığımız İş Bu" : "devamli_yaptiginiz_is_bu"
                                    ]
    var muhalefetDict : NSDictionary = ["Biz Senin Geçmişini Biliriz" : "biz_senin_gecmisini_biliriz",
                                        "Gene Çaktın" : "gene_caktin",
                                        "Avara Kasnak Gibi" : "avara_kasnak_gibi",
                                        "Benim Adım Hıdır" : "benim_adim_hidir",
                                        "Benim Oğlum Bina Okur" : "benim_oglum_bina_okur",
                                        "Maalesef Ders Almıyorlar" : "maalesef_ders_almiyorlar",
                                        "Hadi Yap Hadi" : "hadi_yap_hadi",
                                        "Niye Rahatsız Oluyorsun" : "niye_rahatsiz_oluyorsun",
                                        "Çarpım Tablosunu Tavsiye Ediyorum" : "carpim_tablosunu_tavsiye_ediyorum",
                                        "Anlamaz O İşlerden" : "anlamaz_o_islerden",
                                        "Bu Yalan Söyler Doğru Konuşmaz" : "bu_yalan_soyler_dogru_konusmaz",
                                        "Yürüyen Yalan Görmek İstiyorsanız" : "yuruyen_yalan_gormek_istiyorsaniz",
                                        "Torunlarıma Aldım Faydalı Oldu" : "torunlarima_aldim_faydali_oldu",
                                        "Karsımda Şuanda Bulunuyor" : "karsimda_suanda_bulunuyor",
                                        "Verdiğiniz Sözleri Yerine Getirmediniz" : "verdiginiz_sozleri_yerine_getirmediniz",
                                        "Eşekten Bile Eser Kalıyor" : "esekten_bile_bir_eser_kaliyor",
                                        "Sen Bunu Kürsüden Salla Dur" : "sen_bunu_kursuden_salla_dur",
                                        "Zaten Tek Doğru Lafın O" : "zaten_tek_dogru_lafin_o",
                                        "Nal Topluyorlar Nal" : "nal_topluyorlar_nal",
                                        "Diktadör Olacak Sen Dolaşacaksın Öyle Mi" : "diktator_olacak_sen_dolasacaksin_oyle_mi",
                                        "Sen Ne Anlarsın Helal Haramdan" : "sen_ne_anlarsin_helal_haramdan"
                                
                                       ]
    
    var meydan1Dict : NSDictionary = ["Beraber Yürüdük Biz Bu Yollarda" : "beraber_yuruduk_biz_bu_yollarda",
                                      "Beraber Islandık Yağan Yağmurda" : "beraber_islandik_yagan_yagmurda",
                                      "Şimdi Dinlediğin Tüm Şarkılarda" : "simdi_dinledigim_tum_sarkilarda",
                                      "Bize Herşey Sizi Hatırlatıyor" : "bize_hersey_sizi_hatirlatiyor",
                                      "Bir Olur Bin Diriliriz" : "bir_olur_bin_diriliriz",
                                      "Biz Size Sevdalıyız" : "biz_size_sevdaliyiz",
                                      "Milletin Kaderi Sizin Elinizde Değil" : "milletin_kaderi_sizin_elinizde_degil",
                                      "Millet Kendi Kararını Kendi Verir" : "millet_kendi_kararini_kendi_verir",
                                      "Ya Allah Bismillah" : "ya_allah_bismillah",
                                      "Allah İçin Seviyorum" : "allah_icin_seviyorum",
                                      "BBC Bunuda Gizle" : "bbc_bunuda_gizle",
                                      "CNN Bunuda Gizle" : "cnn_bunuda_gizle",
                                      "Bunuda Gizleyin Olur Mu" : "bunuda_gizleyin_olur_mu",
                                      "Vakit Yok Gideceğiz" : "vakit_yok_gidecegiz",
                                      "Varsın Olmasın" : "varsin_olmasin",
                                      "Varsın Saldırsınlar" : "varsin_saldirsinlar",
                                      "Sizi Gidi Geziciler Sizi" : "sizi_gidi_geziciler_sizi",
                                      "Gezseniz Yine Kar" : "gezseniz_yine_kar",
                                      "Şarkımıza Hazırmıyız" : "sarkimiza_hazirmiyiz",
                                      "Bana Bir Ayran Getirsene" : "bana_bir_ayran_getirsene",
                                      "Hazırmıyız" : "hazirmiyiz",
                                      "Nereden Nereye " : "nereden_nereye",
                                      "Eksiğimiz Var" : "eksigimiz_var",
                                      "Eksiğimizi Acımızı Gidereceğiz" : "eksigimizi_acigimizi_giderecegiz",
                                      "Aman Sabırlı Olun" : "aman_sabirli_olun",
                                      "Adımların Farkında Olmayabilir" : "adimlarin_farkinda_olmayabilir",
                                      "Hep Ölmeyecekmiyiz Ya" : "hep_olmeyecek_miyiz_ya",
                                      "Bunların Akılları Almaz Ha" : "bunlarin_akillari_almaz_ha",
                                      "Hastahane Bulsanız Doktor Bulamazdınız" : "hastahane_bulsaniz_doktor_bulamazdiniz",
                                      "Doktor Bulsanız Cihaz Bulamadınız" : "doktor_bulsaniz_cihaz_bulamazdiniz"
                                    ]
    
    var meydan2Dict : NSDictionary = ["Tek Vatan" : "tek_vatan",
                                      "Tek Millet" : "tek_millet",
                                      "Tek Bayrak" : "tek_bayrak",
                                      "Tek Devlet" : "tek_devlet",
                                      "Bize Dokunan Hesabını İyi Yapsın" : "bize_dokunan_hesabini_iyi_yapsin",
                                      "Hizmetkar Olmaya Geldik" : "hizmetkar_olmaya_geldik",
                                      "Varmı Eğilmek Ya" : "varmi_egilmek_ya",
                                      "Bu Millet Sıradan Bir Millet Değil" : "bu_millet_siradan_bir_millet_degil",
                                      "Bi Dakka Bi Dakka" : "bi_dakka_bi_dakka",
                                      "Biraz Canlanın ya" : "biraz_canlanin_ya",
                                      "Biz O Çileyi Çok Çektik Kızım " : "biz_o_cileyi_cok_cektik_kizim",
                                      "Geçin Bunları Geçin" : "gecin_bunlari_gecin",
                                      "Hala Bekliyorum Anıracak" : "hala_bekliyorum_aniracak",
                                      "Çileyi Anneler Çekiyor" : "cileyi_anneler_cekiyor",
                                      "Şimdi Araları Kıyak" : "simdi_aralari_kiyak",
                                      "Bırakmam Bırakmam" : "birakmam_birakmam",
                                      "Bizim Ablalarımız Burada" : "bizim_ablalarimiz_burada",
                                      "Bizim Abilerimiz Burada" : "bizim_abilerimiz_burada",
                                      "Bu Millet Kabesini Biliyor" : "bu_millet_kabesini_biliyor",
                                      "Ceketimi Çıkarabilirmiyim" : "ceketimi_cikarabilir_miyim",
                                      "Dinime Küfreden Müslüman Olsa" : "dinime_kufreden_musluman_olsa",
                                      "Bize Allah Yeter" : "bize_allah_yeter",
                                      "Karıştırıyorsunuz" : "karistiriyorsunuz",
                                      "Haksızlık Karşısında Susan Dilsiz Şeytandır" : "haksizlik_karsisinda_susan_dilsiz_seytandir",
                                      "Kim Sizin Dertliniz" : "kim_sizin_dertliniz",
                                      "Kim Sizin Sevdalınız" : "kim_sizin_sevdaliniz",
                                      "Biz Dertliyiz" : "biz_dertliyiz",
                                      "Eşek Olur Kalır Semeri" : "esek_olur_kalir_semeri",
                                      "İninize Gireceğiz İninize" : "ininize_girecegiz_ininize",
                                      "Bedduaların Bize Gelmez" : "beddualarin_bize_gelmez",
                                      "Eyy Pensilvanya" : "eyy_pensilvanya",
                                      "Böyle Hoca Olur Mu" : "boyle_hoca_olur_mu"
                                      ]
    var meydan3Dict : NSDictionary = ["Bizim Kardeşliğimiz Ahiret Kardeşliğidir" : "bizim_kardesligimiz_ahiret_kardesligidir",
                                      "Tek Millet Olacağız" : "tek_millet_olacagiz",
                                      "Abidik Gubidik" : "abidik_gubidik",
                                      "Ah Alçaklar Ah" : "ah_alcaklar_ah",
                                      "Bize İkram Edebileceğin Birşey Var Mı" : "bize_ikram_edebilecegin_bir_sey_var_mi",
                                      "Böyle Bir Şey Olabilir Mi" : "boyle_bir_sey_olabilir_mi",
                                      "Kadere Bak" : "kadere_bak",
                                      "Kadere Bak Kimler Kimlerle Beraber" : "kadere_bak_kimler_kimlerle_beraber",
                                      "Sür Eşşeğe Niğdeye" : "sur_essegi_nigdeye",
                                      "Bu Delikanlıda Acayip Ha" : "bu_delikanlida_acayip_ha",
                                      "Olur Veya Olmaz Biz Yolumuza Devam Ediyoruz" : "olur_veya_olmaz_biz_yolumuza_devam_ediyoruz",
                                      "Onu Külahımıza Anlatın" : "onu_kulahimiza_anlatin",
                                      "Alnımızda Enayi Yazmıyor" : "alnimizda_enayi_yazmiyor",
                                      "Men Dakka Dukka" : "men_dakka_dukka",
                                      "Bu Bizim Kanımıza Dokunuyor" : "bu_bizim_kanimiza_dokunuyor",
                                      "Bir Kulağımızdan Girer Öbüründen Çıkar" : "bir_kulagimizdan_girer_oburunden_cikar",
                                      "Şimdi Ben Nobele Sesleniyorum" : "simdi_ben_nobele_sesleniyorum",
                                      "Durmak Yok" : "durmak_yok",
                                      "Biz Buraya Çadırlarımızı Kurduk" : "biz_buraya_cadirlarimizi_kurduk",
                                      "Ben İstediğim Yere Çadır Kurarım" : "ben_istedigim_yere_cadir_kurarim",
                                      "Ama Yine Tencere Tava" : "ama_yine_tencere_tava",
                                      "Tencere Tava Hep Aynı Hava" : "tencere_tava_hep_ayni_hava"
                                     ]
    
    var uluslararasiDict : NSDictionary = ["One Minute" : "one_minute",
                                      "One Minute 2" : "one_minute__2",
                                      "İsrail Barbarlığı" : "israil_barbarligi",
                                      "Öldürmeyi Çok İyi Bilirsiniz" : "oldurmeyi_cok_iyi_bilirsiniz",
                                      "Penceresini Çıkaranların Tırnaklarını Sökeriz" : "pencesini_cikaranlarin_tirnaklarini_sokeriz",
                                      "İslam İle Terör Bir Araya Gelemez" : "islam_ile_teror_bir_araya_gelemez",
                                      "Kimse Bize AKıl Vermeye Kalkmasın" : "kimse_bize_akil_vermeye_kalkmasin",
                                      "O Aklı Kendine Sakla" : "o_akli_kendine_sakla",
                                      "Bizim Çanakkale Destanını Okudunuz Mu" : "bizim_canakkale_destanini_okudunuzmu",
                                      "Vatanı Dar Etmeye Çalışanlara" : "vatani_dar_etmeye_calisanlara",
                                      "Türkiye Kapıkulu Değildir" : "turkiye_kapikulu_degildir",
                                      "Kursağınızda Bırakacağız" : "kursaginizda_birakacagiz",
                                      "Hemen Kararırınızı Verin" : "hemen_kararinizi_verin",
                                      "Geç Kalıyorsun Geç" : "gec_kaliyorsun_gec",
                                      "Geleceğiniz Varsa Göreceğinizde Var" : "geleceginiz_varsa_goreceginizde_var",
                                      "Her Yerin Yaptırım Olsa Ne Yazar" : "her_yerin_yaptirim_olsa_ne_yazar",
                                      "Topunuz Dese Ne Yazar" : "topunuz_dese_ne_yazar",
                                      "Şu Terbiyesize Bak Ya" : "su_terbiyesize_bak_ya",
                                      "Hiçbir Ülke Topraklarında Gözümüz Yok" : "hicbir_ulke_topraklarinda_gozumuz_yok",
                                      "Soykırımı Asla Kabul Etmiyoruz" : "soykirimi_asla_kabul_etmiyoruz",
                                      "Bize Kimse Diplomasi Dersi Vermesin" : "bize_kimse_diplomasi_dersi_vermesin",
                                      "Kimsin Sen Ya" : "kimsin_sen_ya",
                                      "Önce Refik Sonra Tarık" : "once_refik_sonra_tarik",
                                      "Buna Yüreğiniz Yetmez" : "buna_yureginiz_yetmez",
                                      "Bunu Asla Kabul Edemem" : "bunu_asla_kabul_edemem",
                                      "Kötü Komşu İnsanı Hacet Sahibi Yapar" : "kotu_komsu_insani_hacet_sahibi_yapar",
                                      "Bunuda Böyle Bilesin" : "bunuda_boyle_bilesin",
                                      "Daha Davosa Gelmem" : "daha_davosa_gelmem",
                                      "Sanada Çok Teşekkür Ederim" : "sanada_cok_tesekkur_ederim",
                                      "Seksenbeş Koli Belge Gönderdik" : "seksenbes_koli_belge_gonderdik"
                                      ]
    var avrupaDict : NSDictionary = ["Nazizin Yeniden Hortladı" : "nazizim_yeniden_hortladi",
                                      "Faşizimin Ruhu Avrupa Sokaklarında Kol Geziyor" : "fasizimin_ruhu_avrupa_sokaklarinda_kol_geziyor",
                                      "Nazizimin Bittiğini Zannediyordum Devam Ediyormuş" : "nazizimin_bittigini_zannediyordum_devam_ediyormus",
                                      "On Altı Nisan Düşmana Verilecek En Güzel Cevap Olacaktır" : "on_alti_nisan_dusmana_verilecek_en_guzel_cevap_olacaktir",
                                      "Batılılar Geçmişlerindeki Kanı Temizleyemeyecekler" : "batililar_gecmislerindeki_kani_temizleyemeyecekler",
                                      "Avrupa Haydut Devletlere Terkedilemeyecek Kadar Önemlidir" : "avrupa_haydut_devletlere_terkedilemeyecek_kadar_onemlidir",
                                      "Faşistsiniz Faşist" : "fasistsiniz_fasist",
                                      "Biz Hollandayı Srebrenitsa Katliamından Tanırız" : "biz_hollandayi_srebrenitsa_katliamindan_taniriz",
                                      "Senin Heryerin Ab Üyesi Olsa Ne Yazar" : "senin_heryerin_ab_uyesi_olsa_ne_yazar",
                                      "Bunlar Birbirini Isırmaz" : "bunlar_birbirini_isirmaz",
                                      "Neredesin AB" : "neredesin_ab",
                                      "Kimse Bize Medeniyet Dersi Vermesin" : "kimse_bize_medeniyet_dersi_vermesin",
                                      "Ben İstersem Gelirim" : "ben_istersem_gelirim",
                                      "Bizim Önümüzü Kimse Kesemez" : "bizim_onumuzu_kimse_kesemez",
                                      "Haçlı Hilal Mücadelesini Başlattılar" : "hacli_hilal_mucadelesini_baslattilar",
                                      "Bunlar Nazi Kalıntısı" : "bunlar_nazi_kalintisi"
                                      ]
    var basinDict : NSDictionary = ["Beyefendi İzleyememiş" : "beyefendi_izleyememis",
                                      "Soruyorla Kaynak Nedir Diye" : "soruyorlar_kaynak_nedir_diye",
                                      "Akıllı Olun Akıllı" : "akilli_olun_akilli",
                                      "Delikanlıysan Çık Ortaya" : "delikanliysan_cik_ortaya",
                                      "Avucunu Yalarsın Neyi Deviriyorsun" : "avucunu_yalarsin_neyi_deviriyorsun",
                                      "Güneşi Balçıkla Sıvayamaz" : "gunesi_balcikla_sivayamaz",
                                      "Uygun Buluyorsan Hayırlı Olsun" : "uygun_buluyorsan_hayirli_olsun",
                                      "Delikanlı Olun Ciğerimi Yiyin" : "delikanli_olun_cigerimi_yiyin",
                                      "Rahatsız Mı Oldun" : "rahatsiz_mi_oldun",
                                      "Ellerinde Kalem çalakale gidiyorlar" : "ellerinde_kalem_calakalem_gidiyorlar",
                                      "Benim Torunlarım Bırakamıyorlar" : "benim_torunlarim_birakamiyorlar",
                                      "Zorla Tuttuğumuz Yüz Elli Var" : "zorla_tuttugumuz_yuzde_elli_var",
                                      "Kimler Kimlerle El Tutuştu" : "kimler_kimlerle_el_tutustu",
                                      "Hala Bekliyorum Anıracak" : "hala_bekliyorum_aniracak",
                                      "Bize Mağdur Edebiyatı Yapmayın Arkadaş" : "bize_magdur_edebiyati_yapmayin_arkadas",
                                      "Çok Bizimle Uğraştılar" : "cok_bizimle_ugrastilar",
                                      "Senin Bunlardan Haberin Varmı" : "senin_bunlardan_haberin_varmi",
                                      "Benim Bilmediğim Şeyleri Biliyorsunuz" : "benim_bilmedigim_seyleri_biliyorsunuz",
                                      "Sıkıştıracağınızı Zannediyorsan" : "sikistiracagini_zannediyorsan",
                                      "Eğer Üzerime Daha Gelirsen" : "eger_uzerime_daha_gelirsen",
                                      "Sorduklarınız Kolay Mıydı" : "sorduklariniz_kolay_miydi",
                                      "Tarih Bilincin Nedir Senin" : "tarih_bilincin_nedir_senin",
                                      "Böyle Bir İfade Kullanılmaz" : "boyle_bir_ifade_kullanilmaz",
                                      "Ne Gerekçeler Yazmışlar" : "ne_gerekceler_yazmislar",
                                      "Herşeyi Bizden Kapmaya Çalışmayın" : "herseyi_bizden_kapmaya_calismayin",
                                      "Eyy Newyork Times" : "eyy_newyork_times"
                                      ]
    var ekonomiDict : NSDictionary = ["Gereği Neyse Onu Yapın" : "geregi_neyse_onu_yapin",
                                      "Param Var Gaz Yok" : "param_var_gaz_yok",
                                      "Money Money Money" : "money_money_money",
                                      "Patlar Dediler Çatlar Dediler" : "patlar_dediler_catlar_dediler",
                                      "Soydun Soğana Çevirdin Ya" : "soydun_sogana_cevirdin_ya",
                                      "Altı Sıfır Koydular" : "alti_sifir_koydular",
                                      "Parasını Kim Ödüyor" : "parasini_kim_oduyor",
                                      "Yerli Yerli" : "yerli_yerli",
                                      "Hemde Kuzu Kuzu Ödedi" : "hemde_kuzu_kuzu_odedi",
                                      "Teğet Geçecek" : "teget_gececek",
                                      "Türk Lirası Değer Kazansın" : "turk_lirasi_deger_kazansin",
                                      "Hesap Yapıyor Şuanda" : "hesap_yapiyor_suanda",
                                      "Paranı Alıyormusun" : "parani_aliyormusun",
                                      "Sağlıklı Yarınlar İçin" : "saglikli_yarinlar_icin"
                                      ]
    var bunlarDict : NSDictionary = ["Bunlar Dört Dörtlük Cahil" : "bunlar_dort_dortluk_cahil",
                                      "Bunlar Dürüst Değil" : "bunlar_durust_degil",
                                      "Bunlar Çok Zavallı" : "bunlar_cok_zavalli",
                                      "Bunlar İstikameti Şaşırmışlar" : "bunlar_istikameti_sasirmislar",
                                      "Bunlar Sahtekar" : "bunlar_sahtekar",
                                      "Bunlar Şaklaban" : "bunlar_saklaban",
                                      "Bunlar Sandığa İnanmıyor" : "bunlar_sandiga_inanmiyor",
                                      "Bunalr Vatandaşım Olamaz" : "bunlar_vatandasim_olamazlar",
                                      "Bunlar Sapık" : "bunlar_sapik",
                                      "Bunlar Sülük Gibi Emiyorlar" : "bunlar_suluk_gibi_emiyorlar",
                                      "Bunlar Ücretli Şarlatanlar" : "bunlar_ucretli_sarlatanlar",
                                      "Bunlar Zavallı Ya" : "bunlar_zavalli_ya",
                                      "Bunlar Laf Üretiyor Laf" : "bunlar_laf_uretiyor_laf",
                                      "Bunlar Ne Akılsız Adamlar Ya" : "bunlar_ne_akilsiz_adamlar_ya",
                                      "Bunlar Dünyayı Kendi Semtlerinden İbaret Zanneder" : "bunlar_dunyayi_kendi_semtlerinden_ibaret_zanneder",
                                      "Bunlar Belediyeleri Yönetemiyor" : "bunlar_belediyeleri_yonetemiyor",
                                      "Bunlar Monser" : "bunlar_monser",
                                      "Bunlar Kandille Hareket Ediyorlar" : "bunlar_kandille_hareket_ediyorlar",
                                      "Bunlar Terörist" : "bunlar_terorist",
                                      "Bunlar Ateist" : "bunlar_ateist",
                                      "Bunlar Zerdüşt" : "bunlar_zerdust",
                                      "Bunlar Anarşist" : "bunlar_anarsist",
                                      "Bunlarda Edep Adap Yok" : "bunlarda_edep_adap_yok",
                                      "Bunlarda Kök Yok Kök" : "bunlarda_kok_yok_kok",
                                      "Bunlar Haysiyetsiz" : "bunlar_haysiyetsiz",
                                      "Bunlar Namuzsuz" : "bunlar_namussuz",
                                      "Bunların Bizi Tehtidleri Hikaye" : "bunlarin_bizi_tehditleri_hikaye",
                                      "Bunlar Ne Densiz Adamlar Ya" : "bunlar_ne_densiz_adamlar_ya",
                                      "Bunlarda Aşk Yok Sevda Yok" : "bunlarda_ask_yok_sevda_yok",
                                      "Bunlar Ümmeti Parçaladılar" : "bunlar_ummeti_parcaladilar",
                                      "Bunlar Demokrat Değil" : "bunlar_demokrat_degil",
                                      "Bunların Kafası Karanlık" : "bunlarin_kafasi_karanlik",
                                      "Bunlar Çok Yalancı" : "bunlar_cok_yalanci",
                                      "Bunların Cibilliyetini Biliriz" : "bunlarin_cibilliyetini_biliriz",
                                      "Bunlar Kan Kusanlar Değilmi" : "bunlar_kan_kusanlar_degil_mi",
                                      "Bunlar Bölmek İstiyenler Değil mi" : "bunlar_bolmek_isteyenler_degil_mi",
                                      "Buların Ülke Meseleleri İle Dertlendiği Görülmemiştir" : "bunlarin_ulke_meseleleri_ile_dertlendigi_gorulmemistir",
                                      "Bunların Karın Ağrılarını Biliyoruz" : "bunlarin_karin_agrilarini_biliyoruz",
                                      "Bunlar Bölücü Bölücü" : "bunlar_bolucu_bolucu",
                                      "Bunlar Yalan Makinası" : "bunlar_yalan_makinasi",
                                      "Bunlar Yeşili Duman Eder" : "bunlar_yesili_duman_eder",
                                      "Bunlar Yetişemedikleri Üzüme Koruk Der" : "bunlar_yetisemedikleri_uzume_koruk_der",
                                      "Bunların Medenilikle Alakası Yok" : "bunlarin_medenilikle_alakasi_yok",
                                      "Bunlarda Medeniyet Diye Bir Şey Yok" : "bunlarda_medeniyet_diye_birsey_yok",
                                      "Bunlar Varya Bunlar" : "bunlar_varya_bunlar",
                                      "Bunlarda Edep Adap Yok" : "bunlarda_edep_adap_yok"
                                      ]
    var eyyDict : NSDictionary = ["Eyy Allahım Sana Hamdolsun" : "eyy_allahim_sana_hamdolsun",
                                      "Eyy Ana Muhalefetin Temsilcileri" : "eyy_ana_muhalefetin_temsilcileri",
                                      "Eyy Avrupa Birliği" : "eyy_avrupa_birligi",
                                      "Eyy Avrupa Parlementosu" : "eyy_avrupa_parlementosu",
                                      "Eyy Almanya" : "eyy_almanya",
                                      "Eyy Newyork Times" : "eyy_newyork_times",
                                      "Eyy Birleşmiş Milletler" : "eyy_birlesmis_milletler",
                                      "Eyy Alman Siyasiler" : "eyy_alman_siyasileri",
                                      "Eyy Pensilvanya" : "eyy_pensilvanya",
                                      "Eyy Kardeşlerim" : "eyy_kardeslerim",
                                      "Eyy İslam Dünyası" : "eyy_islam_dunyasi",
                                      "Eyy Chp Ve Yandaşları" : "eyy_chp_ve_yandaslari",
                                      "Eyy Kılıçdaroğlu" : "eyy_kilicdaroglu",
                                      "Eyy Kemal" : "eyy_kemal",
                                      "Eyy Metin Feyzioğlu" : "eyy_metin_feyzioglu",
                                      "Eyy Katil Esed" : "eyy_katil_esed",
                                      "Eyy Buna Sessiz Kalan Dünya" : "eyy_buna_sessiz_kalan_dunya",
                                      "Eyy Geziciler" : "eyy_geziciler",
                                      "Eyy Chp Yönetimi" : "eyy_chp_yonetimi",
                                      "Eyy Benim Saadet Partili Kardeşlerim" : "eyy_benim_saadet_partili_kardeslerim",
                                      "Eyy Ulusalcılar" : "eyy_ulusalcilar",
                                      "Eyy Nobel" : "eyy_nobel",
                                      "Eyy Rutte" : "eyy_rutte",
                                      "Eyy Gafil" : "eyy_gafil",
                                      "Eyy Cahil" : "eyy_cahil",
                                      "Eyy Aziz İstanbul" : "eyy_aziz_istanbul",
                                      "Eyy Trabzon" : "eyy_trabzon"
                                      ]
    var karadenizagziDict : NSDictionary = ["Allahinuza Kurban Olayım" : "allahinuza_kurban_olayim",
                                      "Ben Ne Edeceğum" : "ben_ne_edecegum",
                                      "Bi Dur Da Bi Dur" : "bi_dur_da_bi_dur",
                                      "Bi Daha Aç Bakayım" : "bi_daha_ac_bakayim",
                                      "Birbirinizi Üzmek Yok Ha" : "birbirinizi_uzmek_yok_ha",
                                      "O Ne Dediyse Onu Yap" : "o_ne_dediyse_onu_yap",
                                      "Oy Benum Sevdiceğum" : "oy_benum_sevdicegum",
                                      "Rizenin Uşaklarının Aklına Gelen" : "rizenin_usaklarinin_aklina_gelen",
                                      "Sen Bizi Bi Dinle Da" : "sen_bizi_bi_dinle_da",
                                      "Sesiniz Çıkması Yoksa Bilememeniz" : "sesiniz_cikmai_yoksa_bilmeimisiniz",
                                      "Ula Bu Bayraktur Bayrak" : "ula_bu_bayraktur_bayrak",
                                      "Ne Tuzluğa Ne Çaydanluğa" : "ne_tuzluga_ne_caydanluga",
                                      "Ula Sen Ne İşe Yararsun" : "ula_sen_ne_ise_yararsun",
                                      "Agasar Dereleri Bulanık Akayisun" : "agasar_dereleri_bulanik_akayisun"
                                      ]
    var temmuz15Dict : NSDictionary = ["Başaramayacaksınız" : "basaramayacaksiniz",
                                      "Ezanlarımızı Susturamayacaksınız" : "ezanlarimizi_susturamayacaksiniz",
                                      "Bu Ülkede Şehitler Tepesi Boş Kalmıyor" : "bu_ulkede_sehitler_tepesi_bos_kalmiyor",
                                      "Şehitler Tepesi Boş Değil" : "sehitler_tepesi_bos_degil",
                                      "Biz Biriz Beraberiz Hep Birlikte Türkiyeyiz" : "biz_biriz_beraberiz_hep_birlikte_turkiyeyiz",
                                      "Biz NE Kutlu Bir Milletiz" : "biz_ne_kutlu_bir_milletiz",
                                      "Allah Tuzak Kuranların En Hayırlısıdır" : "allah_tuzak_kuranlarin_en_hayirlisidir",
                                      "Yeniden İstiklal Mücadelesi Veriyoruz" : "yeniden_istikbal_mucadelesi_veriyoruz",
                                      "Pkk Feto Deas Pyd Ypg Topunuz Gelin" : "pkk_feto_daes_pyd_ypg_topunuz_gelin",
                                      "Rabbim Bu Milleti Korusun" : "rabbim_bu_milleti_korusun",
                                      "Milletimizi Meydanlara Davet Ediyorum" : "milletimizi_meydanlara_davet_ediyorum",
                                      "Halkın Gücü Üstünde Bir Güç Tanımadım" : "halkin_gucu_ustunde_bir_guc_tanimadim",
                                      "Şeytanın Aklına Gelmeyen Bunların Aklına Gelir" : "seytanin_aklina_gelmeyen_bunlarin_aklina_gelir",
                                      "Bunuda Ancak Kafirler Yapar" : "bunuda_ancak_kafirler_yapar"
                                      ]
    
    var referandumDict : NSDictionary = ["Evet Evet Evet" : "evet_evet_evet",
                                      "Evete Hazırmıyız" : "evete_hazirmiyiz",
                                      "Atı Alan Üsküdarı Geçti" : "ati_alan_uskudara_gecti",
                                      "Evetinize Kurban Olayım" : "evetinize_kurban_olayim",
                                      "Alnına Karıslarlar Alnını" : "alnini_karislarlar_alnini",
                                      "Yunan Mı Ulan Bu" : "yunan_mi_ulan_bu",
                                      "Ulan Seni Yola Çıkarmazlar" : "ulan_seni_yola_cikarmazlar",
                                      "Bunlar Türlerinin Son Örneği" : "bunlar_turlerinin_son_ornegi",
                                      "Terör Örgütlerini Tercih Edenlere Cevap Veriyormuyuz" : "teror_orgutlerini_tercih_edenlere_cevap_veriyormuyuz",
                                      "Batının Asalaklarını Atmaya Varmıyız" : "batinin_asalaklarini_atmaya_varmiyiz",
                                      "Koprü Yaptık Hayır Dediler" : "kopru_yaptik_hayir_dediler",
                                      "Onlar Hayır Dedi Diye Biz Duracakmıyız" : "onlar_hayir_dedi_diye_biz_duracakmiyiz",
                                      "On Altı Nisan Bizim İçin Devrimdir" : "on_alti_nisan_bizim_icin_devrimdir",
                                      "Çılgın Türkleri Durduramayacaksınız" : "cilgin_turkleri_durduramayacaksiniz",
                                      "Sen Kimi Denize Döküyorsun Terbiyesiz" : "sen_kimi_denize_dokuyorsun_terbiyesiz",
                                      "Terbiyesizliklerinin Altında Bin Yıllık Karın Ağrılarının Yattığını Biliyoruz" : "terbiyesizliklerinin_altinda_bin_yillik_karin_agrilarinin_yattigini_biliyoruz",
                                      "Hans Ne Der Beni Enterese Etmez" : "hans_ne_der_beni_enterese_etmez",
                                      "Kimler Hayır Diyor" : "kimler_hayir_diyor",
                                      "Yav Sen Gerizekalımısın" : "yav_sen_gerizekalimisin",
                                      "Bunlar Türlerinin Son Örneği" : "bunlar_turlerinin_son_ornegi"
                                      ]
    
    var fullDataDict : NSDictionary = [
        "Bakınız" : "bakiniz",
        "Annesi Bu Beni Niye Bu Kadar Çok Seviyor" : "annesi_bu_beni_niye_bu_kadar_cok_seviyor",
        "Çok Sevindim" : "cok_sevindim",
        "Hoşgeldiniz" : "hosgeldiniz",
        "Ciddimi Diyorsun" : "ciddimi_diyorsun",
        "Bak Neler Söylüyor Neler" : "bak_neler_soyluyor_neler",
        "Ne Yapayım Ben Bunu" : "ne_yapayim_ben_bunu",
        "Elinize Sağlık" : "elinize_saglik",
        "Yok Ya" : "yok_ya",
        "Ey Gidi Günler" : "ey_gidi_gunler",
        "Herkes İşin Lafında" : "herkes_isin_lafinda",
        "Öldürdü Beni Be" : "oldurdu_beni_be",
        "Olmaz Olmaz" : "olmaz_olmaz",
        "Böyle Geldik Böyle Gidiyoruz" : "boyle_geldik_boyle_gidiyoruz",
        "Eyy Kardeşlerim" : "eyy_kardeslerim",
        "Zor Geliyor Kardeşim" : "zor_geliyor_kardasim",
        "Geçiktim Hakkınızı Helal Edin" : "geciktim_hakkinizi_helal_edin",
        "Haklısınız" : "haklisiniz",
        "Kalın Sağlıcakla" : "kalin_saglicakla",
        "Bende Şaşırdım" : "bende_sasirdim",
        "Aman Sabırlı Olun" : "aman_sabirli_olun",
        "Ve Aleyküm Selam" : "ve_aleykum_selam",
        "Alan Götürdü Alan Götürdü" : "alan_goturdu_alan_goturdu",
        "Aldatmayın Çocukları" : "aldatmayin_cocuklari",
        "Bu Nasıl Bir Anlayıştır" : "bu_nasil_bir_anlayistir",
        "Bu Ne Biçim İştir" : "bu_ne_bicim_istir",
        "Eh Sallana Sallana" : "eh_sallana_sallana",
        "Ya Ben Demedim" : "ya_ben_demedim",
        "Geçin Bunları Geçin" : "gecin_bunlari_gecin",
        "Kimi Aldatıyorusunuz Ya" : "kimi_aldatiyorsunuz_ya",
        "Ama Ya Rabbim" : "aman_ya_rabbim",
        "Size Ne Ya" : "size_ne_ya",
        "Onlar Mazide Kaldı" : "onlar_mazide_kaldi",
        "Öyle Bir Haykır Ki" : "oyle_bir_haykir_ki",
        "Cirit Atıyor Cirit" : "cirit_atiyor_cirit",
        "Ne Yaptınız" : "ne_yaptiniz",
        "Geçti O" : "gecti_o",
        "OOOO" : "oooo",
        "Neyy" : "neyy",
        "Ah" : "ah_ah",
        "Sabah Dört Buçuğa Kadar Konuşuyoruz":"sabah_dort_bucuga_kadar_konusuyoruz",
        "Maaşallah Allah Nazardan Saklasın":"maasallah_allah_nazardan_saklasin",
        "Vah Zavallı Vah":"vah_zavalli_vah",
        "Bıktık Ya Bıktık":"biktik_ya_biktik",
        "Yazıklar Olsun Sizlere":"yaziklar_olsun_sizlere",
        "Yalan Konuşma Be":"yalan_konusma_be",
        "Ben Seni Varya Bu Kadar Seviyorum":"ben_seni_varya_bu_kadar_seviyorum",
        "Reisim Neredeyiz Biliyormusun":"reisim_neredeyiz_biliyormusun",
        "Gençler Gençler":"gencler_gencler",
        "Ders Çalış Ders":"ders_calis_ders",
        "Nadani Terk Etmedin Yarani Arzularsın":"nadani_terk_etmedin_yarani_arzularsin",
        "Biz Nadanı Terk Ettik Yaranı Bulduk":"biz_nadani_terk_ettik_yarani_bulduk",
        "Kızlar Kızlar":"kizlar_kizlar",
        "Ya Sanane Ya":"ya_sanane_ya",
        "Estaizubilllah Bismillah":"estaizubillah_bismillah",
        "Ne Diyor Bu Adam Ya":"ne_diyor_bu_adam_ya",
        "Ne Oldum Deme Ne Olacağım De":"ne_oldum_deme_ne_olacagim_de",
        "Ne Yapacağınızı Biliyorsunuz Değil Mi":"ne_yapacaginizi_biliyorsunuz_degil_mi",
        "Selamun Aleyküm" : "selamun_aleykum",
        "Seni Saygıyla Selamlıyorum" : "seni_saygiyla_selamliyorum",
        "Seni Gönül Dolusu Muhabbet ile Selamlıyorum" : "seni_gonul_dolusu_muhabbet_ile_selamliyorum",
        "Senin Gidecek Yerin Yok Be" : "senin_gidecek_yerin_yok_be",
        "Sakin Olun" : "sakin_olun",
        "Sen Kimsin Ya" : "sen_kimsin_ya",
        "Allah Kabul Etsin" : "allah_kabul_etsin",
        "Geliyorum Şimdi" : "geliyorum_simdi",
        "Doğrusu Şevkini Kırmak İstemiyorum" : "dogrusu_sevkini_kirmak_istemiyorum",
        "Görüyormusun Burada Bile Selfie Yapıyor" : "goruyormusun_burada_bile_selfie_yapiyor",
        "Hadi Oradan Ahlaksız" : "hadi_oradan_ahlaksiz",
        "Hadi Gülüm Yandan Yandan" : "hadi_gulum_yandan_yandan",
        "Ne Olacak" : "ne_olacak",
        "Olsun Be" : "olsun_be",
        "Kafaya Bak Ya" : "kafaya_bak_ya",
        "Ben Senin EEEE" : "ben_senin_eeee",
        "Bakalım Göreceğiz" : "bakalim_gorecegiz",
        "Bene Bak Akedes" : "bene_bak_akedes",
        "Maaşallahınız Var" : "maasallahiniz_var",
        "Buyrun Buyrun Buyrun" : "buyrun_buyrun_buyrun",
        "Bak Bak Bak" : "bak_bak_bak",
        "Yerinde Duramıyor" : "yerinde_duramiyor",
        "Ağlarım Anlatamam" : "aglarim_anlatamam",
        "Hissederim Söyleyemem" : "hissederim_soyleyemem",
        "Burası Enteresan" : "burasi_enteresan",
        "Boşuna Uğraşmayın" : "bosuna_ugrasmayin",
        "Biz Ölümüne" : "biz_olumune",
        "Şaka Maka Baya Seyircim Varmış" : "saka_maka_baya_seyircim_varmis",
        "Nereye Hitap Edileceğini Bilirim" : "nereye_hitap_edilecegini_bilirim",
        "Bitmedi Bak" : "bitmedi_bak",
        "Bunlar Dürüst Değil" : "bunlar_durust_degil",
        "Çok Konuşuyorsun" : "cok_konusuyorsun",
        "Bu Kürsülerin Acemisiniz" : "bu_kursulerin_acemisisiniz",
        "Siz Mi Susturacaksınız Ben Mi Susturayım" : "siz_mi_susturacaksiniz_ben_mi_susturayim",
        "Onu Özele Gelirsin Anlatırım Sana" : "onu_ozele_gelirsin_anlatirim_sana",
        "Ne Yapayım Ben Bunu" : "ne_yapayim_ben_bunu",
        "Nabza Göre Şerbet Veriyorlar" : "nabza_gore_serbet_veriyorlar",
        "Tahriklerinize Gelecek Değilim" : "tahriklerinize_gelecek_degilim",
        "İşte Bu Olmadı" : "iste_bu_olmadi",
        "Baki Kalan Bu Kubbede Hoş Bir Sada İmiş" : "baki_kalan_bu_kubbede_hos_bir_sada_imis",
        "Lütfen Susarmısınız Lütfen" : "lutfen_susar_misiniz_lutfen",
        "Hoplama Rahat Ol" : "hoplama_rahat_ol",
        "Niye Rahatsız Oluyorsun" : "niye_rahatsiz_oluyorsun",
        "Okulu Asıp Haysızlığa Gitmişler" : "okulu_asip_haylazliga_gitmisler",
        "Az Önce Bir İfade Kullanıldı" : "az_once_bir_ifade_kullanildi",
        "Ben Sayıyorum" : "ben_sayiyorum",
        "Artık Ciddi Olarak Ele Alalım" : "artik_ciddi_olarak_ele_alalim",
        "Al Hepsi Burada" : "al_hepsi_burada",
        "Önce Başkanını Davet Et" : "once_baskanini_davet_et",
        "Kara Bulut Gibi Çöktü" : "kara_bulut_gibi_coktu",
        "Geçiken Adalet Adalet Değildir" : "geciken_adalet_adalet_degildir",
        "Devamlı Yaptığımız İş Bu" : "devamli_yaptiginiz_is_bu",
        "Biz Senin Geçmişini Biliriz" : "biz_senin_gecmisini_biliriz",
        "Gene Çaktın" : "gene_caktin",
        "Avara Kasnak Gibi" : "avara_kasnak_gibi",
        "Benim Adım Hıdır" : "benim_adim_hidir",
        "Benim Oğlum Bina Okur" : "benim_oglum_bina_okur",
        "Maalesef Ders Almıyorlar" : "maalesef_ders_almiyorlar",
        "Hadi Yap Hadi" : "hadi_yap_hadi",
        "Niye Rahatsız Oluyorsun" : "niye_rahatsiz_oluyorsun",
        "Çarpım Tablosunu Tavsiye Ediyorum" : "carpim_tablosunu_tavsiye_ediyorum",
        "Anlamaz O İşlerden" : "anlamaz_o_islerden",
        "Bu Yalan Söyler Doğru Konuşmaz" : "bu_yalan_soyler_dogru_konusmaz",
        "Yürüyen Yalan Görmek İstiyorsanız" : "yuruyen_yalan_gormek_istiyorsaniz",
        "Torunlarıma Aldım Faydalı Oldu" : "torunlarima_aldim_faydali_oldu",
        "Karsımda Şuanda Bulunuyor" : "karsimda_suanda_bulunuyor",
        "Verdiğiniz Sözleri Yerine Getirmediniz" : "verdiginiz_sozleri_yerine_getirmediniz",
        "Eşekten Bile Eser Kalıyor" : "esekten_bile_bir_eser_kaliyor",
        "Sen Bunu Kürsüden Salla Dur" : "sen_bunu_kursuden_salla_dur",
        "Zaten Tek Doğru Lafın O" : "zaten_tek_dogru_lafin_o",
        "Nal Topluyorlar Nal" : "nal_topluyorlar_nal",
        "Diktadör Olacak Sen Dolaşacaksın Öyle Mi" : "diktator_olacak_sen_dolasacaksin_oyle_mi",
        "Sen Ne Anlarsın Helal Haramdan" : "sen_ne_anlarsin_helal_haramdan",
        "Beraber Yürüdük Biz Bu Yollarda" : "beraber_yuruduk_biz_bu_yollarda",
        "Beraber Islandık Yağan Yağmurda" : "beraber_islandik_yagan_yagmurda",
        "Şimdi Dinlediğin Tüm Şarkılarda" : "simdi_dinledigim_tum_sarkilarda",
        "Bize Herşey Sizi Hatırlatıyor" : "bize_hersey_sizi_hatirlatiyor",
        "Bir Olur Bin Diriliriz" : "bir_olur_bin_diriliriz",
        "Biz Size Sevdalıyız" : "biz_size_sevdaliyiz",
        "Milletin Kaderi Sizin Elinizde Değil" : "milletin_kaderi_sizin_elinizde_degil",
        "Millet Kendi Kararını Kendi Verir" : "millet_kendi_kararini_kendi_verir",
        "Ya Allah Bismillah" : "ya_allah_bismillah",
        "Allah İçin Seviyorum" : "allah_icin_seviyorum",
        "BBC Bunuda Gizle" : "bbc_bunuda_gizle",
        "CNN Bunuda Gizle" : "cnn_bunuda_gizle",
        "Bunuda Gizleyin Olur Mu" : "bunuda_gizleyin_olur_mu",
        "Vakit Yok Gideceğiz" : "vakit_yok_gidecegiz",
        "Varsın Olmasın" : "varsin_olmasin",
        "Varsın Saldırsınlar" : "varsin_saldirsinlar",
        "Sizi Gidi Geziciler Sizi" : "sizi_gidi_geziciler_sizi",
        "Gezseniz Yine Kar" : "gezseniz_yine_kar",
        "Şarkımıza Hazırmıyız" : "sarkimiza_hazirmiyiz",
        "Bana Bir Ayran Getirsene" : "bana_bir_ayran_getirsene",
        "Hazırmıyız" : "hazirmiyiz",
        "Nereden Nereye " : "nereden_nereye",
        "Eksiğimiz Var" : "eksigimiz_var",
        "Eksiğimizi Acımızı Gidereceğiz" : "eksigimizi_acigimizi_giderecegiz",
        "Aman Sabırlı Olun" : "aman_sabirli_olun",
        "Adımların Farkında Olmayabilir" : "adimlarin_farkinda_olmayabilir",
        "Hep Ölmeyecekmiyiz Ya" : "hep_olmeyecek_miyiz_ya",
        "Bunların Akılları Almaz Ha" : "bunlarin_akillari_almaz_ha",
        "Hastahane Bulsanız Doktor Bulamazdınız" : "hastahane_bulsaniz_doktor_bulamazdiniz",
        "Doktor Bulsanız Cihaz Bulamadınız" : "doktor_bulsaniz_cihaz_bulamazdiniz",
        "Tek Vatan" : "tek_vatan",
        "Tek Millet" : "tek_millet",
        "Tek Bayrak" : "tek_bayrak",
        "Tek Devlet" : "tek_devlet",
        "Bize Dokunan Hesabını İyi Yapsın" : "bize_dokunan_hesabini_iyi_yapsin",
        "Hizmetkar Olmaya Geldik" : "hizmetkar_olmaya_geldik",
        "Varmı Eğilmek Ya" : "varmi_egilmek_ya",
        "Bu Millet Sıradan Bir Millet Değil" : "bu_millet_siradan_bir_millet_degil",
        "Bi Dakka Bi Dakka" : "bi_dakka_bi_dakka",
        "Biraz Canlanın ya" : "biraz_canlanin_ya",
        "Biz O Çileyi Çok Çektik Kızım " : "biz_o_cileyi_cok_cektik_kizim",
        "Geçin Bunları Geçin" : "gecin_bunlari_gecin",
        "Hala Bekliyorum Anıracak" : "hala_bekliyorum_aniracak",
        "Çileyi Anneler Çekiyor" : "cileyi_anneler_cekiyor",
        "Şimdi Araları Kıyak" : "simdi_aralari_kiyak",
        "Bırakmam Bırakmam" : "birakmam_birakmam",
        "Bizim Ablalarımız Burada" : "bizim_ablalarimiz_burada",
        "Bizim Abilerimiz Burada" : "bizim_abilerimiz_burada",
        "Bu Millet Kabesini Biliyor" : "bu_millet_kabesini_biliyor",
        "Ceketimi Çıkarabilirmiyim" : "ceketimi_cikarabilir_miyim",
        "Dinime Küfreden Müslüman Olsa" : "dinime_kufreden_musluman_olsa",
        "Bize Allah Yeter" : "bize_allah_yeter",
        "Karıştırıyorsunuz" : "karistiriyorsunuz",
        "Haksızlık Karşısında Susan Dilsiz Şeytandır" : "haksizlik_karsisinda_susan_dilsiz_seytandir",
        "Kim Sizin Dertliniz" : "kim_sizin_dertliniz",
        "Kim Sizin Sevdalınız" : "kim_sizin_sevdaliniz",
        "Biz Dertliyiz" : "biz_dertliyiz",
        "Eşek Olur Kalır Semeri" : "esek_olur_kalir_semeri",
        "İninize Gireceğiz İninize" : "ininize_girecegiz_ininize",
        "Bedduaların Bize Gelmez" : "beddualarin_bize_gelmez",
        "Eyy Pensilvanya" : "eyy_pensilvanya",
        "Böyle Hoca Olur Mu" : "boyle_hoca_olur_mu",
        "Bizim Kardeşliğimiz Ahiret Kardeşliğidir" : "bizim_kardesligimiz_ahiret_kardesligidir",
        "Tek Millet Olacağız" : "tek_millet_olacagiz",
        "Abidik Gubidik" : "abidik_gubidik",
        "Ah Alçaklar Ah" : "ah_alcaklar_ah",
        "Bize İkram Edebileceğin Birşey Var Mı" : "bize_ikram_edebilecegin_bir_sey_var_mi",
        "Böyle Bir Şey Olabilir Mi" : "boyle_bir_sey_olabilir_mi",
        "Kadere Bak" : "kadere_bak",
        "Kadere Bak Kimler Kimlerle Beraber" : "kadere_bak_kimler_kimlerle_beraber",
        "Sür Eşşeğe Niğdeye" : "sur_essegi_nigdeye",
        "Bu Delikanlıda Acayip Ha" : "bu_delikanlida_acayip_ha",
        "Olur Veya Olmaz Biz Yolumuza Devam Ediyoruz" : "olur_veya_olmaz_biz_yolumuza_devam_ediyoruz",
        "Onu Külahımıza Anlatın" : "onu_kulahimiza_anlatin",
        "Alnımızda Enayi Yazmıyor" : "alnimizda_enayi_yazmiyor",
        "Men Dakka Dukka" : "men_dakka_dukka",
        "Bu Bizim Kanımıza Dokunuyor" : "bu_bizim_kanimiza_dokunuyor",
        "Bir Kulağımızdan Girer Öbüründen Çıkar" : "bir_kulagimizdan_girer_oburunden_cikar",
        "Şimdi Ben Nobele Sesleniyorum" : "simdi_ben_nobele_sesleniyorum",
        "Durmak Yok" : "durmak_yok",
        "Biz Buraya Çadırlarımızı Kurduk" : "biz_buraya_cadirlarimizi_kurduk",
        "Ben İstediğim Yere Çadır Kurarım" : "ben_istedigim_yere_cadir_kurarim",
        "Ama Yine Tencere Tava" : "ama_yine_tencere_tava",
        "Tencere Tava Hep Aynı Hava" : "tencere_tava_hep_ayni_hava",
        "One Minute" : "one_minute",
        "One Minute 2" : "one_minute__2",
        "İsrail Barbarlığı" : "israil_barbarligi",
        "Öldürmeyi Çok İyi Bilirsiniz" : "oldurmeyi_cok_iyi_bilirsiniz",
        "Penceresini Çıkaranların Tırnaklarını Sökeriz" : "pencesini_cikaranlarin_tirnaklarini_sokeriz",
        "İslam İle Terör Bir Araya Gelemez" : "islam_ile_teror_bir_araya_gelemez",
        "Kimse Bize AKıl Vermeye Kalkmasın" : "kimse_bize_akil_vermeye_kalkmasin",
        "O Aklı Kendine Sakla" : "o_akli_kendine_sakla",
        "Bizim Çanakkale Destanını Okudunuz Mu" : "bizim_canakkale_destanini_okudunuzmu",
        "Vatanı Dar Etmeye Çalışanlara" : "vatani_dar_etmeye_calisanlara",
        "Türkiye Kapıkulu Değildir" : "turkiye_kapikulu_degildir",
        "Kursağınızda Bırakacağız" : "kursaginizda_birakacagiz",
        "Hemen Kararırınızı Verin" : "hemen_kararinizi_verin",
        "Geç Kalıyorsun Geç" : "gec_kaliyorsun_gec",
        "Geleceğiniz Varsa Göreceğinizde Var" : "geleceginiz_varsa_goreceginizde_var",
        "Her Yerin Yaptırım Olsa Ne Yazar" : "her_yerin_yaptirim_olsa_ne_yazar",
        "Topunuz Dese Ne Yazar" : "topunuz_dese_ne_yazar",
        "Şu Terbiyesize Bak Ya" : "su_terbiyesize_bak_ya",
        "Hiçbir Ülke Topraklarında Gözümüz Yok" : "hicbir_ulke_topraklarinda_gozumuz_yok",
        "Soykırımı Asla Kabul Etmiyoruz" : "soykirimi_asla_kabul_etmiyoruz",
        "Bize Kimse Diplomasi Dersi Vermesin" : "bize_kimse_diplomasi_dersi_vermesin",
        "Kimsin Sen Ya" : "kimsin_sen_ya",
        "Önce Refik Sonra Tarık" : "once_refik_sonra_tarik",
        "Buna Yüreğiniz Yetmez" : "buna_yureginiz_yetmez",
        "Bunu Asla Kabul Edemem" : "bunu_asla_kabul_edemem",
        "Kötü Komşu İnsanı Hacet Sahibi Yapar" : "kotu_komsu_insani_hacet_sahibi_yapar",
        "Bunuda Böyle Bilesin" : "bunuda_boyle_bilesin",
        "Daha Davosa Gelmem" : "daha_davosa_gelmem",
        "Sanada Çok Teşekkür Ederim" : "sanada_cok_tesekkur_ederim",
        "Seksenbeş Koli Belge Gönderdik" : "seksenbes_koli_belge_gonderdik",
        "Nazizin Yeniden Hortladı" : "nazizim_yeniden_hortladi",
        "Faşizimin Ruhu Avrupa Sokaklarında Kol Geziyor" : "fasizimin_ruhu_avrupa_sokaklarinda_kol_geziyor",
        "Nazizimin Bittiğini Zannediyordum Devam Ediyormuş" : "nazizimin_bittigini_zannediyordum_devam_ediyormus",
        "On Altı Nisan Düşmana Verilecek En Güzel Cevap Olacaktır" : "on_alti_nisan_dusmana_verilecek_en_guzel_cevap_olacaktir",
        "Batılılar Geçmişlerindeki Kanı Temizleyemeyecekler" : "batililar_gecmislerindeki_kani_temizleyemeyecekler",
        "Avrupa Haydut Devletlere Terkedilemeyecek Kadar Önemlidir" : "avrupa_haydut_devletlere_terkedilemeyecek_kadar_onemlidir",
        "Faşistsiniz Faşist" : "fasistsiniz_fasist",
        "Biz Hollandayı Srebrenitsa Katliamından Tanırız" : "biz_hollandayi_srebrenitsa_katliamindan_taniriz",
        "Senin Heryerin Ab Üyesi Olsa Ne Yazar" : "senin_heryerin_ab_uyesi_olsa_ne_yazar",
        "Bunlar Birbirini Isırmaz" : "bunlar_birbirini_isirmaz",
        "Neredesin AB" : "neredesin_ab",
        "Kimse Bize Medeniyet Dersi Vermesin" : "kimse_bize_medeniyet_dersi_vermesin",
        "Ben İstersem Gelirim" : "ben_istersem_gelirim",
        "Bizim Önümüzü Kimse Kesemez" : "bizim_onumuzu_kimse_kesemez",
        "Haçlı Hilal Mücadelesini Başlattılar" : "hacli_hilal_mucadelesini_baslattilar",
        "Bunlar Nazi Kalıntısı" : "bunlar_nazi_kalintisi",
        "Beyefendi İzleyememiş" : "beyefendi_izleyememis",
        "Soruyorla Kaynak Nedir Diye" : "soruyorlar_kaynak_nedir_diye",
        "Akıllı Olun Akıllı" : "akilli_olun_akilli",
        "Delikanlıysan Çık Ortaya" : "delikanliysan_cik_ortaya",
        "Avucunu Yalarsın Neyi Deviriyorsun" : "avucunu_yalarsin_neyi_deviriyorsun",
        "Güneşi Balçıkla Sıvayamaz" : "gunesi_balcikla_sivayamaz",
        "Uygun Buluyorsan Hayırlı Olsun" : "uygun_buluyorsan_hayirli_olsun",
        "Delikanlı Olun Ciğerimi Yiyin" : "delikanli_olun_cigerimi_yiyin",
        "Rahatsız Mı Oldun" : "rahatsiz_mi_oldun",
        "Ellerinde Kalem çalakale gidiyorlar" : "ellerinde_kalem_calakalem_gidiyorlar",
        "Benim Torunlarım Bırakamıyorlar" : "benim_torunlarim_birakamiyorlar",
        "Zorla Tuttuğumuz Yüz Elli Var" : "zorla_tuttugumuz_yuzde_elli_var",
        "Kimler Kimlerle El Tutuştu" : "kimler_kimlerle_el_tutustu",
        "Hala Bekliyorum Anıracak" : "hala_bekliyorum_aniracak",
        "Bize Mağdur Edebiyatı Yapmayın Arkadaş" : "bize_magdur_edebiyati_yapmayin_arkadas",
        "Çok Bizimle Uğraştılar" : "cok_bizimle_ugrastilar",
        "Senin Bunlardan Haberin Varmı" : "senin_bunlardan_haberin_varmi",
        "Benim Bilmediğim Şeyleri Biliyorsunuz" : "benim_bilmedigim_seyleri_biliyorsunuz",
        "Sıkıştıracağınızı Zannediyorsan" : "sikistiracagini_zannediyorsan",
        "Eğer Üzerime Daha Gelirsen" : "eger_uzerime_daha_gelirsen",
        "Sorduklarınız Kolay Mıydı" : "sorduklariniz_kolay_miydi",
        "Tarih Bilincin Nedir Senin" : "tarih_bilincin_nedir_senin",
        "Böyle Bir İfade Kullanılmaz" : "boyle_bir_ifade_kullanilmaz",
        "Ne Gerekçeler Yazmışlar" : "ne_gerekceler_yazmislar",
        "Herşeyi Bizden Kapmaya Çalışmayın" : "herseyi_bizden_kapmaya_calismayin",
        "Eyy Newyork Times" : "eyy_newyork_times",
        "Gereği Neyse Onu Yapın" : "geregi_neyse_onu_yapin",
        "Param Var Gaz Yok" : "param_var_gaz_yok",
        "Money Money Money" : "money_money_money",
        "Patlar Dediler Çatlar Dediler" : "patlar_dediler_catlar_dediler",
        "Soydun Soğana Çevirdin Ya" : "soydun_sogana_cevirdin_ya",
        "Altı Sıfır Koydular" : "alti_sifir_koydular",
        "Parasını Kim Ödüyor" : "parasini_kim_oduyor",
        "Yerli Yerli" : "yerli_yerli",
        "Hemde Kuzu Kuzu Ödedi" : "hemde_kuzu_kuzu_odedi",
        "Teğet Geçecek" : "teget_gececek",
        "Türk Lirası Değer Kazansın" : "turk_lirasi_deger_kazansin",
        "Hesap Yapıyor Şuanda" : "hesap_yapiyor_suanda",
        "Paranı Alıyormusun" : "parani_aliyormusun",
        "Sağlıklı Yarınlar İçin" : "saglikli_yarinlar_icin",
        "Bunlar Dört Dörtlük Cahil" : "bunlar_dort_dortluk_cahil",
        "Bunlar Dürüst Değil" : "bunlar_durust_degil",
        "Bunlar Çok Zavallı" : "bunlar_cok_zavalli",
        "Bunlar İstikameti Şaşırmışlar" : "bunlar_istikameti_sasirmislar",
        "Bunlar Sahtekar" : "bunlar_sahtekar",
        "Bunlar Şaklaban" : "bunlar_saklaban",
        "Bunlar Sandığa İnanmıyor" : "bunlar_sandiga_inanmiyor",
        "Bunalr Vatandaşım Olamaz" : "bunlar_vatandasim_olamazlar",
        "Bunlar Sapık" : "bunlar_sapik",
        "Bunlar Sülük Gibi Emiyorlar" : "bunlar_suluk_gibi_emiyorlar",
        "Bunlar Ücretli Şarlatanlar" : "bunlar_ucretli_sarlatanlar",
        "Bunlar Zavallı Ya" : "bunlar_zavalli_ya",
        "Bunlar Laf Üretiyor Laf" : "bunlar_laf_uretiyor_laf",
        "Bunlar Ne Akılsız Adamlar Ya" : "bunlar_ne_akilsiz_adamlar_ya",
        "Bunlar Dünyayı Kendi Semtlerinden İbaret Zanneder" : "bunlar_dunyayi_kendi_semtlerinden_ibaret_zanneder",
        "Bunlar Belediyeleri Yönetemiyor" : "bunlar_belediyeleri_yonetemiyor",
        "Bunlar Monser" : "bunlar_monser",
        "Bunlar Kandille Hareket Ediyorlar" : "bunlar_kandille_hareket_ediyorlar",
        "Bunlar Terörist" : "bunlar_terorist",
        "Bunlar Ateist" : "bunlar_ateist",
        "Bunlar Zerdüşt" : "bunlar_zerdust",
        "Bunlar Anarşist" : "bunlar_anarsist",
        "Bunlarda Edep Adap Yok" : "bunlarda_edep_adap_yok",
        "Bunlarda Kök Yok Kök" : "bunlarda_kok_yok_kok",
        "Bunlar Haysiyetsiz" : "bunlar_haysiyetsiz",
        "Bunlar Namuzsuz" : "bunlar_namussuz",
        "Bunların Bizi Tehtidleri Hikaye" : "bunlarin_bizi_tehditleri_hikaye",
        "Bunlar Ne Densiz Adamlar Ya" : "bunlar_ne_densiz_adamlar_ya",
        "Bunlarda Aşk Yok Sevda Yok" : "bunlarda_ask_yok_sevda_yok",
        "Bunlar Ümmeti Parçaladılar" : "bunlar_ummeti_parcaladilar",
        "Bunlar Demokrat Değil" : "bunlar_demokrat_degil",
        "Bunların Kafası Karanlık" : "bunlarin_kafasi_karanlik",
        "Bunlar Çok Yalancı" : "bunlar_cok_yalanci",
        "Bunların Cibilliyetini Biliriz" : "bunlarin_cibilliyetini_biliriz",
        "Bunlar Kan Kusanlar Değilmi" : "bunlar_kan_kusanlar_degil_mi",
        "Bunlar Bölmek İstiyenler Değil mi" : "bunlar_bolmek_isteyenler_degil_mi",
        "Buların Ülke Meseleleri İle Dertlendiği Görülmemiştir" : "bunlarin_ulke_meseleleri_ile_dertlendigi_gorulmemistir",
        "Bunların Karın Ağrılarını Biliyoruz" : "bunlarin_karin_agrilarini_biliyoruz",
        "Bunlar Bölücü Bölücü" : "bunlar_bolucu_bolucu",
        "Bunlar Yalan Makinası" : "bunlar_yalan_makinasi",
        "Bunlar Yeşili Duman Eder" : "bunlar_yesili_duman_eder",
        "Bunlar Yetişemedikleri Üzüme Koruk Der" : "bunlar_yetisemedikleri_uzume_koruk_der",
        "Bunların Medenilikle Alakası Yok" : "bunlarin_medenilikle_alakasi_yok",
        "Bunlarda Medeniyet Diye Bir Şey Yok" : "bunlarda_medeniyet_diye_birsey_yok",
        "Bunlar Varya Bunlar" : "bunlar_varya_bunlar",
        "Bunlarda Edep Adap Yok" : "bunlarda_edep_adap_yok",
        "Eyy Allahım Sana Hamdolsun" : "eyy_allahim_sana_hamdolsun",
        "Eyy Ana Muhalefetin Temsilcileri" : "eyy_ana_muhalefetin_temsilcileri",
        "Eyy Avrupa Birliği" : "eyy_avrupa_birligi",
        "Eyy Avrupa Parlementosu" : "eyy_avrupa_parlementosu",
        "Eyy Almanya" : "eyy_almanya",
        "Eyy Newyork Times" : "eyy_newyork_times",
        "Eyy Birleşmiş Milletler" : "eyy_birlesmis_milletler",
        "Eyy Alman Siyasiler" : "eyy_alman_siyasileri",
        "Eyy Pensilvanya" : "eyy_pensilvanya",
        "Eyy Kardeşlerim" : "eyy_kardeslerim",
        "Eyy İslam Dünyası" : "eyy_islam_dunyasi",
        "Eyy Chp Ve Yandaşları" : "eyy_chp_ve_yandaslari",
        "Eyy Kılıçdaroğlu" : "eyy_kilicdaroglu",
        "Eyy Kemal" : "eyy_kemal",
        "Eyy Metin Feyzioğlu" : "eyy_metin_feyzioglu",
        "Eyy Katil Esed" : "eyy_katil_esed",
        "Eyy Buna Sessiz Kalan Dünya" : "eyy_buna_sessiz_kalan_dunya",
        "Eyy Geziciler" : "eyy_geziciler",
        "Eyy Chp Yönetimi" : "eyy_chp_yonetimi",
        "Eyy Benim Saadet Partili Kardeşlerim" : "eyy_benim_saadet_partili_kardeslerim",
        "Eyy Ulusalcılar" : "eyy_ulusalcilar",
        "Eyy Nobel" : "eyy_nobel",
        "Eyy Rutte" : "eyy_rutte",
        "Eyy Gafil" : "eyy_gafil",
        "Eyy Cahil" : "eyy_cahil",
        "Eyy Aziz İstanbul" : "eyy_aziz_istanbul",
        "Eyy Trabzon" : "eyy_trabzon",
        "Allahinuza Kurban Olayım" : "allahinuza_kurban_olayim",
        "Ben Ne Edeceğum" : "ben_ne_edecegum",
        "Bi Dur Da Bi Dur" : "bi_dur_da_bi_dur",
        "Bi Daha Aç Bakayım" : "bi_daha_ac_bakayim",
        "Birbirinizi Üzmek Yok Ha" : "birbirinizi_uzmek_yok_ha",
        "O Ne Dediyse Onu Yap" : "o_ne_dediyse_onu_yap",
        "Oy Benum Sevdiceğum" : "oy_benum_sevdicegum",
        "Rizenin Uşaklarının Aklına Gelen" : "rizenin_usaklarinin_aklina_gelen",
        "Sen Bizi Bi Dinle Da" : "sen_bizi_bi_dinle_da",
        "Sesiniz Çıkması Yoksa Bilememeniz" : "sesiniz_cikmai_yoksa_bilmeimisiniz",
        "Ula Bu Bayraktur Bayrak" : "ula_bu_bayraktur_bayrak",
        "Ne Tuzluğa Ne Çaydanluğa" : "ne_tuzluga_ne_caydanluga",
        "Ula Sen Ne İşe Yararsun" : "ula_sen_ne_ise_yararsun",
        "Agasar Dereleri Bulanık Akayisun" : "agasar_dereleri_bulanik_akayisun",
        "Başaramayacaksınız" : "basaramayacaksiniz",
        "Ezanlarımızı Susturamayacaksınız" : "ezanlarimizi_susturamayacaksiniz",
        "Bu Ülkede Şehitler Tepesi Boş Kalmıyor" : "bu_ulkede_sehitler_tepesi_bos_kalmiyor",
        "Şehitler Tepesi Boş Değil" : "sehitler_tepesi_bos_degil",
        "Biz Biriz Beraberiz Hep Birlikte Türkiyeyiz" : "biz_biriz_beraberiz_hep_birlikte_turkiyeyiz",
        "Biz NE Kutlu Bir Milletiz" : "biz_ne_kutlu_bir_milletiz",
        "Allah Tuzak Kuranların En Hayırlısıdır" : "allah_tuzak_kuranlarin_en_hayirlisidir",
        "Yeniden İstiklal Mücadelesi Veriyoruz" : "yeniden_istikbal_mucadelesi_veriyoruz",
        "Pkk Feto Deas Pyd Ypg Topunuz Gelin" : "pkk_feto_daes_pyd_ypg_topunuz_gelin",
        "Rabbim Bu Milleti Korusun" : "rabbim_bu_milleti_korusun",
        "Milletimizi Meydanlara Davet Ediyorum" : "milletimizi_meydanlara_davet_ediyorum",
        "Halkın Gücü Üstünde Bir Güç Tanımadım" : "halkin_gucu_ustunde_bir_guc_tanimadim",
        "Şeytanın Aklına Gelmeyen Bunların Aklına Gelir" : "seytanin_aklina_gelmeyen_bunlarin_aklina_gelir",
        "Bunuda Ancak Kafirler Yapar" : "bunuda_ancak_kafirler_yapar",
        "Evet Evet Evet" : "evet_evet_evet",
        "Evete Hazırmıyız" : "evete_hazirmiyiz",
        "Atı Alan Üsküdarı Geçti" : "ati_alan_uskudara_gecti",
        "Evetinize Kurban Olayım" : "evetinize_kurban_olayim",
        "Alnına Karıslarlar Alnını" : "alnini_karislarlar_alnini",
        "Yunan Mı Ulan Bu" : "yunan_mi_ulan_bu",
        "Ulan Seni Yola Çıkarmazlar" : "ulan_seni_yola_cikarmazlar",
        "Bunlar Türlerinin Son Örneği" : "bunlar_turlerinin_son_ornegi",
        "Terör Örgütlerini Tercih Edenlere Cevap Veriyormuyuz" : "teror_orgutlerini_tercih_edenlere_cevap_veriyormuyuz",
        "Batının Asalaklarını Atmaya Varmıyız" : "batinin_asalaklarini_atmaya_varmiyiz",
        "Koprü Yaptık Hayır Dediler" : "kopru_yaptik_hayir_dediler",
        "Onlar Hayır Dedi Diye Biz Duracakmıyız" : "onlar_hayir_dedi_diye_biz_duracakmiyiz",
        "On Altı Nisan Bizim İçin Devrimdir" : "on_alti_nisan_bizim_icin_devrimdir",
        "Çılgın Türkleri Durduramayacaksınız" : "cilgin_turkleri_durduramayacaksiniz",
        "Sen Kimi Denize Döküyorsun Terbiyesiz" : "sen_kimi_denize_dokuyorsun_terbiyesiz",
        "Terbiyesizliklerinin Altında Bin Yıllık Karın Ağrılarının Yattığını Biliyoruz" : "terbiyesizliklerinin_altinda_bin_yillik_karin_agrilarinin_yattigini_biliyoruz",
        "Hans Ne Der Beni Enterese Etmez" : "hans_ne_der_beni_enterese_etmez",
        "Kimler Hayır Diyor" : "kimler_hayir_diyor",
        "Yav Sen Gerizekalımısın" : "yav_sen_gerizekalimisin",
        "Bunlar Türlerinin Son Örneği" : "bunlar_turlerinin_son_ornegi"


        
        
        ]
    
    
    
    
    
    
    
    
    
    
    
    
    
    

}
